# ==========================================
# This is Dummy Data for Dev server how it is worked okkk
# ==========================================

spring:
  application:
    name: ingestion-worker-service

  datasource:
    url: jdbc:postgresql://sonymusic-dev-db.abcdefgh1234.us-east-1.rds.amazonaws.com:5432/sonymusic_dev
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers:
      - b-1.msk-devcluster.abcd.kafka.us-east-1.amazonaws.com:9092
      - b-2.msk-devcluster.abcd.kafka.us-east-1.amazonaws.com:9092

  redis:
    host: sonymusic-dev-redis.abcd.use1.cache.amazonaws.com
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://discovery-dev:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: https://xray.us-east-1.amazonaws.com
