global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'metadata-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['metadata-service:8081']

  - job_name: 'search-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['search-service:8082']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway-service:8080']
